---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Use the latest stable version
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf] # This is the key: convert all line endings to LF (Unix style)
        # You can also use --fix=crlf to convert all to CRLF (Windows style)
        # Or --fix=auto to let pre-commit decide based on the majority line ending in the file.
        # --fix=lf is generally recommended for cross-platform projects stored in Git.
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn", "--confidence=HIGH"]
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        types: [yaml]
        args: ["-d", "{extends: relaxed, rules: {line-length: {max: 120}}}"]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [sh, csh]
        args: ["-i", "SC2154"]
