---
name: Prepare Github Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: build mkdocs for github pages and deploy to the branch gh-pages
        run: |
          git fetch --depth 10 origin +refs/heads/*:refs/remotes/origin/*
          mkdocs gh-deploy
